package com.example.techquiz;

public class ai {
    public static String question[] ={
            "1.The “Father of Artificial Intelligence” is:",
            "2.Blind Search can be used for which of the following situations?",
            "3.In how many category processes is Artificial Intelligence classified in?",
            "4.If a machine can change its course of action based on the external environment on its own, the machine is called?",
            "5.Which of the following is the common language for Artificial Intelligence?",
            "6.Which of the following techniques is used in natural language processing?",
            "7.What is the purpose of a convolutional neural network?",
            "8.Which algorithm is used for unsupervised learning?",
            "9.Which of the following is an example of a reinforcement learning application?",
            "10.What is the purpose of transfer learning in machine learning?",
            "11.Which of the following is a supervised learning algorithm?",
            "12.Which of the following techniques is used for feature extraction in image processing?",
            "13.Which of the following is used for anomaly detection?",
            "14.Which of the following techniques is used for data imputation?",
            "15.What is the purpose of batch normalization in deep learning?",
            "16.Which of the following is a deep learning framework?",
            "17.Which of the following techniques is used for time series forecasting?",
            "18.Which of the following is used for text classification?",
            "19.What is the primary goal of artificial intelligence?",
            "20.Which of the following is not a subfield of artificial intelligence?",
            "21.Which technique is commonly used to train machine learning models?",
            "22.What is the purpose of an artificial neural network?",
            "23.Which programming language is commonly used in AI research?",
            "24.What is the role of an activation function in a neural network?",
            "25.Which algorithm is used to classify data into two or more categories?",
            "26.Which technique is used to extract meaningful information from unstructured text data",
            "27.Which approach aims to mimic human cognitive processes in AI systems?",
            "28.What is the purpose of a recommendation system?",
            "29.Which technique is used to find the optimal solution in a search problem?",
            "30.Which algorithm is used to update the weights of a neural network during training?",

    };

    public static String choices[][] = {
            {"Alan_Turing","Charles_Babbage","John_McCarthy","None_Of_the_above"},
            {"Real_Life_Simulation","Small_Search_Space"," Advanced_Game_Theory","None_of_the_above"},
            {"Depends_on_the_input_nature","5","2","3"},
            {"Mobile","Intelligent","Both_A_and_B","None_of_the_above"},
            {"Python","Java","Lisp","PHP"},
            {"Decision trees","Genetic algorithms","Neural networks","Support vector machines"},
            {"Text classification","Object detection","Reinforcement learning","Speech recognition"},
            {"Naive Bayes","Decision tree","K-means clustering","Random forest"},
            {"Image classification","Stock market prediction","Game-playing","Sentiment analysis"},
            {"To reuse a pre-trained model for a new task","To improve the performance of a model on a specific task","To combine multiple models to make a prediction","To preprocess data before training a model"},
            {"K-means clustering","Linear regression","Apriori algorithm","Principal component analysis"},
            {"Principal component analysis","Convolutional neural networks","K-means clustering","Naive Bayes"},
            {"Support vector machines","K-nearest neighbors","Decision trees","Random forest"},
            {"Naive Bayes","Principal component analysis","K-nearest neighbors","Decision trees"},
            {"To normalize the input data before training","To reduce overfitting in the model","To improve the speed of training","dTo regularize the weights of the model"},
            {"Scikit-learn","TensorFlow","OpenCV","NLTK"},
            {"Decision trees"," Linear regression","ARIMA","Support vector machines"},
            {"Convolutional neural networks","Apriori algorithm","K-means clustering","Principal component analysis"},
            {"Mimic human intelligence","Solve complex mathematical problems","Create autonomous robots\n","Improve computer performance"},
            {"Machine learning","Natural language processin","Computer vision","Web development"},
            {"Reinforcement learning","Supervised learning","Unsupervised learning","Genetic algorithms"},
            {"Speech recognition","Object detection","Image classification","All of the above"},
            {"Python","Java","C++","Ruby"},
            {"Normalize the input data","Calculate the error between predicted and actual values","Introduce non-linearity to the network\n","Update the weights during training"},
            {"Linear regression","K-means clustering","Decision tree","Principal component analysis"},
            {" Image recognition","Speech synthesis","Sentiment analysis","Reinforcement learning"},
            {"Logical reasoning","Heuristic search","Symbolic AI","Genetic algorithms"},
            {"Predict future stock prices","Detect anomalies in network traffic","Generate personalized product suggestions","Translate languages in real-time"},
            {"Depth-first search","Breadth-first search","A* algorithm","Reinforcement learning"},
            {"Backpropagation","Genetic algorithm","Gradient descent","Naive Bayes"},

    };

    public static String correctAnswers[] = {
            "John_McCarthy",
            "Small_Search_Space",
            "3",
            "Intelligent",
            "Python",
            "Neural networks",
            "K-means clustering",
            "Game-playing",
            "To reuse a pre-trained model for a new task",
            "Linear regression",
            "Convolutional neural networks",
            "Support vector machines",
            "K-nearest neighbors",
            "To reduce overfitting in the model",
            "TensorFlow",
            "ARIMA",
            "Convolutional neural networks",
            "Mimic human intelligence",
            "Web development",
            "Supervised learning",
            "All of the above",
            "Python",
            "Introduce non-linearity to the network",
            "Decision tree",
            "Sentiment analysis",
            "Symbolic AI",
            "Generate personalized product suggestions",
            "A* algorithm",
            "Backpropagation",

    };

}