package com.example.techquiz;

public class aptitudeqs {

    public static String question[] ={
            "1.What is the value of 3 + 5 * 2?",
            "2.If a car travels at a constant speed of 60 km/h, how far will it travel in 3 hours?\n",
            "3.If 4 workers can complete a job in 6 days, how many days will it take for 6 workers to complete the same job?",
            "4.Solve the equation: 2x + 5 = 15",
            "5.A store offers a 20% discount on a $50 shirt. What is the sale price?",
            "6.If the perimeter of a rectangle is 24 units and its length is 6 units, what is its width?",
            "7.What is the square root of 144?",
            "8.Simplify: (3 + 4) × 2 - 5.",
            "9.If 3 cats catch 3 mice in 3 minutes, how many cats are needed to catch 100 mice in 100 minutes?",
            "10.What is 30% of 200?",
            "11.If a square has an area of 49 square units, what is the length of one side?",
            "12.A bike is sold for $300 at a loss of 20%. What is the cost price of the bike?",
            "13.Solve the equation: 2(3x - 4) = 10.",
            "14.A train travels from station A to station B at a speed of 80 km/h and returns to station A at a speed of 60 km/h. What is the average speed for the entire journey?",
            "15.A sum of money doubles itself in 5 years at simple interest. How many years will it take to become 8 times the original sum at the same rate of interest?",
            "16.In a group of people, 60% like ice cream, 50% like cake, and 40% like both ice cream and cake. What percentage of the group likes neither ice cream nor cake?",
            "17.The cost price of an item is $100. If it is sold at a profit of 20%, what will be the selling price?",
            "18.A car takes 8 seconds to accelerate uniformly from rest to a speed of 72 km/h. What is the distance covered during this time?",
            "19.If a man cycles at a speed of 10 km/h, he reaches his destination 30 minutes late. If he cycles at a speed of 12 km/h, he reaches 15 minutes early. What is the distance to his destination?",
            "20.A can complete a task in 15 days, while B can complete the same task in 10 days. If they work together for 5 days and then A leaves, how many more days will it take for B to complete the remaining task?",
            "21.What is the value of (2^3)^2 × 2^4 - 2^5?",
            "22.A shopkeeper sells an article at a 20% discount and still makes a profit of 25%. If the cost price of the article is $100, what is the selling price?",
            "23.A train travels at a speed of 60 km/h for the first hour, 70 km/h for the second hour, and 80 km/h for the third hour. What is the average speed of the train for the entire journey?",
            "24.A shop sells a pair of shoes for $80, making a profit of 25%. What is the cost price of the shoes?",
            "25.The ratio of the present ages of two people is 3:5. If the sum of their ages is 40, what is the age of the older person?",
            "26.A square field has an area of 144 square meters. What is the perimeter of the field?",
            "27.A boat can travel 30 km upstream in 6 hours and the same distance downstream in 4 hours. What is the speed of the boat in still water?",
            "28.In an examination, 40% of the students failed and 75% of the remaining students passed. If the number of students who failed was 120, how many students took the examination?",
            "29.A boat can travel 30 km upstream in 6 hours and the same distance downstream in 4 hours. What is the speed of the boat in still water?",
            "30.In an examination, 40% of the students failed and 75% of the remaining students passed. If the number of students who failed was 120, how many students took the examination?"
    };

    public static String choices[][] = {
            {"13","16","11","8"},
            {"150kms","120kms","180kms","90kms"},
            {"3","8","4","9"},
            {"x=6","x=5","x=7","x=8"},
            {"$40","$45","$50","$60"},
            {"4 units","6 units","3 units","8 units"},
            {"9","10","12","16"},
            {"11","14","15","12"},
            {"1","10","3","100"},
            {"60","50","70","80"},
            {"4 units","7 units","9 units","14 units"},
            {"$350","$375","$400","$500"},
            {"x=1","x=2","x=3","x=4"},
            {"66 km/h","70 km/h","72 km/h","75 km/h"},
            {"15 years","20 years","25 years","30 years"},
            {"10%","20%","30%","40%"},
            {"$120","$110","$105","$104"},
            {"160 m","200 m","240 m","280 m"},
            {"12 km","15 km","18 km","20 km"},
            {"4 days","5 days","6 days","8 days"},
            {"12","32","48","64"},
            {"$80","$85","$90","$95"},
            {"70 km/h","75 km/h","77 km/h","80 km/h"},
            {"$60","$64","$70","$75"},
            {"20","25","30","35"},
            {"36 meters","48 meters","56 meters","60 meters"},
            {"7.5 km/h","8 km/h","9 km/h","10 km/h"},
            {"200","300","400","500"},
            {"7.5 km/h","8 km/h","9 km/h","10 km/h"},
            {"200","300","400","500"}
    };

    public static String correctAnswers[] = {
            "16",
            "180kms",
            "4",
            "x=6",
            "$45",
            "3 units",
            "12",
            "11",
            "1",
            "60",
            "7 units",
            "400",
            "x=2",
            "66 km/h",
            "20 years",
            "20%",
            "$120",
            "240 m",
            "18 km",
            "5 days",
            "48",
            "$95",
            "77 km/h",
            "$60",
            "35",
            "56 meters",
            "8 km/h",
            "400",
            "8 km/h",
            "400"
    };

}


